name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci    - name: Create .env file
      run: |
        echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
        echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
        echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
        echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
        echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
        echo "VITE_SQUARE_APPLICATION_ID=${{ secrets.VITE_SQUARE_APPLICATION_ID }}" >> .env
        echo "VITE_SQUARE_ACCESS_TOKEN=${{ secrets.VITE_SQUARE_ACCESS_TOKEN }}" >> .env
        echo "VITE_SQUARE_ENVIRONMENT=${{ secrets.VITE_SQUARE_ENVIRONMENT }}" >> .env
        echo "VITE_PERPLEXITY_API_KEY=${{ secrets.VITE_PERPLEXITY_API_KEY }}" >> .env

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        channelId: live
